source ~/.zplug/zplug

zplug "mafredri/zsh-async", nice:13

zplug "zsh-users/zsh-syntax-highlighting", nice:10
zplug "zsh-users/zsh-completions", nice:11
zplug "zsh-users/zsh-history-substring-search", nice:12
zplug "willghatch/zsh-saneopt"
zplug "hoffi/zsh-theme-lambda"
zplug "hoffi/zsh-git-aliases", if:"which git"
zplug "djui/alias-tips", nice:11
zplug "Tarrasch/zsh-autoenv", nice:14
zplug "supercrabtree/k", nice:15
zplug "junegunn/fzf"
zplug "zsh-users/zsh-autosuggestions"
zplug "trapd00r/LS_COLORS", of:"LS_COLORS", as:command, nice:16
zplug "~/.zsh", from:local, file:"*.zsh"

if ! zplug check --verbose; then
  printf "Install? [y/N]: "
  if read -q; then
    echo; zplug install
  fi
fi
zplug load

export XDG_CONFIG_HOME="$HOME/.config"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

source ~/Development/Fuze/github/git-subrepo/.rc

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"
[[ -s /Users/nferreira/.fast/scripts/profile_local ]] && source /Users/nferreira/.fast/scripts/profile_local
